# docker-compose.yml
version: "2.1"
services:
  app:
    build: .
    volumes:
    - .:/home/app
    - /home/app/node_modules
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3033:3033"
      - "9229:9229"
    environment:
      PSQL_HOST: 0.0.0.0
      PSQL_PASSWORD: postgres
      PSQL_USER: docker
      PSQL_DATABASE: sandbox
      PSQL_DATABASE_TEST: test

  postgres:
    image: postgres:11.7-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./src/worker/script/init_additional_databases.sql:/docker-entrypoint-initdb.d/init_additional_databases.sql
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD: postgres
