# docker-compose.yml
version: "3"
services:
  app:
    build: .
    volumes:
    - .:/home/app
    - /home/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3033:3033"
      - "9229:9229"
    environment:
      PSQL_HOST: postgres
      PSQL_PASSWORD: postgres
      PSQL_USER: docker
      PSQL_DATABASE: sandbox
      PSQL_DATABASE_TEST: test

  postgres:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: sandbox
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    ports:
    - "8080:8080"
